/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import  cafe_management_system.model.user;
import  cafe_management_system.dao.UserDao;

/**
 *
 * @author Pradnya Jadhav
 */
public class forgetpassword extends javax.swing.JFrame
{
    private String dbans = null;
    private String email = null;
    private String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public forgetpassword()
    {
        initComponents();
        setLocationRelativeTo(null);
        btnlogin.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\login.png"));
        btnclear2.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\clear.png"));
        btnsearch.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\search.png"));
        btnupdate.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\save.png"));
        btnexit.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\exit.png"));
        lblbackground.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\background6.PNG"));
        btnupdate.setEnabled(false);
        btnsearch.setEnabled(false);
       
        
    }

    public void clear()
   {
       txtans.setText("");
       txtemail.setText("");
       txtnewpassword.setText("");
       lblbackground.setText("");
       btnupdate.setEnabled(false);
       btnsearch.setEnabled(false);
       
   }
    public void validateemail()
    {
        email = txtemail.getText();
        if(email.matches(emailPattern))
        {
            btnsearch.setEnabled(true);
        }
        else
        {
            btnsearch.setEnabled(false);
        }
    }
    public void validateFields()
    {
        String secuirity= lblbackground.getText();
        String dummyemail=txtemail.getText();
        String newpassword = txtnewpassword.getText();
        String ans = txtans.getText();
        if(!secuirity.equals("") && dummyemail.matches(emailPattern) && !newpassword.equals("")  && !ans.equals("") )
        {
            btnupdate.setEnabled(true);
        }
        else
        {
            btnupdate.setEnabled(false);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblsecuirity = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblans = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtans = new javax.swing.JTextField();
        txtnewpassword = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnclear2 = new javax.swing.JButton();
        txtsecurity = new javax.swing.JTextField();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 620));

        jPanel1.setMinimumSize(new java.awt.Dimension(1270, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 620));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("FORGOT PASSWORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 120, 300, 40);

        lblemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblemail.setForeground(new java.awt.Color(0, 0, 0));
        lblemail.setText("Email");
        jPanel1.add(lblemail);
        lblemail.setBounds(350, 210, 90, 21);

        lblsecuirity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblsecuirity.setForeground(new java.awt.Color(0, 0, 0));
        lblsecuirity.setText("Your Security Question");
        jPanel1.add(lblsecuirity);
        lblsecuirity.setBounds(350, 260, 200, 21);

        lblpassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 0, 0));
        lblpassword.setText("New Password");
        jPanel1.add(lblpassword);
        lblpassword.setBounds(350, 380, 120, 16);

        lblans.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblans.setForeground(new java.awt.Color(0, 0, 0));
        lblans.setText("Your Answer");
        jPanel1.add(lblans);
        lblans.setBounds(350, 320, 160, 21);

        txtemail.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtemailKeyReleased(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(580, 200, 420, 30);

        txtans.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtans.setForeground(new java.awt.Color(0, 0, 0));
        txtans.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtansKeyReleased(evt);
            }
        });
        jPanel1.add(txtans);
        txtans.setBounds(580, 320, 420, 30);

        txtnewpassword.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtnewpassword.setForeground(new java.awt.Color(0, 0, 0));
        txtnewpassword.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtnewpasswordActionPerformed(evt);
            }
        });
        txtnewpassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtnewpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtnewpassword);
        txtnewpassword.setBounds(580, 380, 420, 30);

        btnupdate.setBackground(new java.awt.Color(1, 1, 21));
        btnupdate.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(580, 430, 100, 40);

        btnexit.setBackground(new java.awt.Color(1, 1, 21));
        btnexit.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(910, 430, 90, 40);

        btnlogin.setBackground(new java.awt.Color(1, 1, 21));
        btnlogin.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(910, 490, 90, 40);

        btnsignup.setBackground(new java.awt.Color(1, 1, 21));
        btnsignup.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignup);
        btnsignup.setBounds(580, 490, 90, 40);

        btnsearch.setBackground(new java.awt.Color(1, 1, 21));
        btnsearch.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch);
        btnsearch.setBounds(1060, 200, 100, 40);

        btnclear2.setBackground(new java.awt.Color(1, 1, 21));
        btnclear2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnclear2.setForeground(new java.awt.Color(255, 255, 255));
        btnclear2.setText("Clear");
        btnclear2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnclear2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear2);
        btnclear2.setBounds(730, 430, 90, 40);

        txtsecurity.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtsecurity.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtsecurity);
        txtsecurity.setBounds(580, 262, 420, 30);
        jPanel1.add(lblbackground);
        lblbackground.setBounds(0, 0, 1270, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtemailActionPerformed
    {//GEN-HEADEREND:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnupdateActionPerformed
    {//GEN-HEADEREND:event_btnupdateActionPerformed
        String answer = txtans.getText();
        String newPassword = txtans.getText();
        if(answer.equals(dbans))
        {
           UserDao.update(email, newPassword);
           clear();
           txtsecurity.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"<html>,b style=\"color:red\">Incorrect Answer</b></html>","Message",JOptionPane.ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnexitActionPerformed
    {//GEN-HEADEREND:event_btnexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnloginActionPerformed
    {//GEN-HEADEREND:event_btnloginActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsignupActionPerformed
    {//GEN-HEADEREND:event_btnsignupActionPerformed
        setVisible(false);
        new signup().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsearchActionPerformed
    {//GEN-HEADEREND:event_btnsearchActionPerformed
        email = txtemail.getText();
        user user = null;
        user = UserDao.getSecurityQuestion(email);
        if(user == null)
        {
            JOptionPane.showMessageDialog(null,"<html><b style=\"color:red\">Incorrect Email</b></html>","Message",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            btnsearch.setEnabled(false);
            txtemail.setEditable(false);
            dbans= user.getAns();
            txtsecurity.setText(user.getSecurity());
            validateFields();
           
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtnewpasswordActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtnewpasswordActionPerformed
    {//GEN-HEADEREND:event_txtnewpasswordActionPerformed
        validateFields();                
    }//GEN-LAST:event_txtnewpasswordActionPerformed

    private void btnclear2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnclear2ActionPerformed
    {//GEN-HEADEREND:event_btnclear2ActionPerformed
        clear();
        txtsecurity.setText("");
    }//GEN-LAST:event_btnclear2ActionPerformed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtemailKeyReleased
    {//GEN-HEADEREND:event_txtemailKeyReleased
        validateemail();
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtansKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtansKeyReleased
    {//GEN-HEADEREND:event_txtansKeyReleased
        validateFields();
    }//GEN-LAST:event_txtansKeyReleased

    private void txtnewpasswordKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnewpasswordKeyReleased
    {//GEN-HEADEREND:event_txtnewpasswordKeyReleased
        validateFields();
        btnupdate.setEnabled(true);
    }//GEN-LAST:event_txtnewpasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new forgetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear2;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblans;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblsecuirity;
    private javax.swing.JTextField txtans;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnewpassword;
    private javax.swing.JTextField txtsecurity;
    // End of variables declaration//GEN-END:variables
}
