/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pradnya Jadhav
 */
public class home extends javax.swing.JFrame
{

    /**
     * Creates new form home
     */
    public String email;
    public home()
    {
        initComponents();
        setLocationRelativeTo(this);
        lblIcon.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\background7.jpg"));
        btnLogout.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\logout.png"));
        btnChangePass.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\change Password.png"));
        
        btnExit.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\exit.png"));
        btnPlaceOrder.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\place order.png"));
        btnViewBill.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\View Bills & Order Placed Details.png"));
        btnManagerCategory.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\category.png"));
        btnViewEditDelete.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\view edit delete product.png"));
        btnNewProduct.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\new product.png"));
        
    }
    public home(String userEmail)
    {
        initComponents();
        setLocationRelativeTo(this);
        lblIcon.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\background7.jpg"));
        btnLogout.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\logout.png"));
        btnChangePass.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\change Password.png"));
        
        btnExit.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\exit.png"));
        btnPlaceOrder.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\place order.png"));
        btnViewBill.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\View Bills & Order Placed Details.png"));
        btnManagerCategory.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\category.png"));
        btnViewEditDelete.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\view edit delete product.png"));
        
        btnNewProduct.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\new product.png"));
        email = userEmail;
        if(!email.equals("admin@gmail.com"))
        {
            btnManagerCategory.setVisible(false);
            btnNewProduct.setVisible(false);
            btnViewEditDelete.setVisible(false);
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnLogout = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnViewBill = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnManagerCategory = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        btnViewEditDelete = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 766));
        setPreferredSize(new java.awt.Dimension(1366, 766));
        setResizable(false);
        getContentPane().setLayout(null);

        btnLogout.setBackground(new java.awt.Color(51, 0, 0));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout);
        btnLogout.setBounds(860, 30, 260, 40);

        btnChangePass.setBackground(new java.awt.Color(51, 0, 0));
        btnChangePass.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass);
        btnChangePass.setBounds(590, 30, 260, 40);

        btnPlaceOrder.setBackground(new java.awt.Color(51, 0, 0));
        btnPlaceOrder.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder);
        btnPlaceOrder.setBounds(320, 30, 260, 40);

        btnViewBill.setBackground(new java.awt.Color(51, 0, 0));
        btnViewBill.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewBill.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBill.setText("View Bill & Order Placed Details");
        btnViewBill.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBill);
        btnViewBill.setBounds(10, 30, 300, 40);

        btnExit.setBackground(new java.awt.Color(51, 0, 0));
        btnExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1130, 30, 190, 40);

        btnManagerCategory.setBackground(new java.awt.Color(51, 0, 0));
        btnManagerCategory.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnManagerCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerCategory.setText("Manager Category");
        btnManagerCategory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnManagerCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagerCategory);
        btnManagerCategory.setBounds(950, 680, 290, 40);

        btnNewProduct.setBackground(new java.awt.Color(51, 0, 0));
        btnNewProduct.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNewProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewProduct);
        btnNewProduct.setBounds(580, 680, 290, 40);

        btnViewEditDelete.setBackground(new java.awt.Color(51, 0, 0));
        btnViewEditDelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnViewEditDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEditDelete.setText("View,Edit & Delete Product");
        btnViewEditDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewEditDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEditDelete);
        btnViewEditDelete.setBounds(210, 680, 290, 40);
        getContentPane().add(lblIcon);
        lblIcon.setBounds(-4, 0, 1780, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLogoutActionPerformed
    {//GEN-HEADEREND:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to close application?","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnManagerCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnManagerCategoryActionPerformed
    {//GEN-HEADEREND:event_btnManagerCategoryActionPerformed
        setVisible(false);
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnManagerCategoryActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewProductActionPerformed
    {//GEN-HEADEREND:event_btnNewProductActionPerformed
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnViewEditDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewEditDeleteActionPerformed
    {//GEN-HEADEREND:event_btnViewEditDeleteActionPerformed
        setVisible(false);
        new viewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnViewEditDeleteActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlaceOrderActionPerformed
    {//GEN-HEADEREND:event_btnPlaceOrderActionPerformed
      
        setVisible(false);
        new placeOrder(email).setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnViewBillActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewBillActionPerformed
    {//GEN-HEADEREND:event_btnViewBillActionPerformed
        setVisible(false);
        new ViewBillsOrderPlacedDetails().setVisible(true);
    }//GEN-LAST:event_btnViewBillActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangePassActionPerformed
    {//GEN-HEADEREND:event_btnChangePassActionPerformed
        setVisible(false);
        new ChangePassword().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagerCategory;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnViewBill;
    private javax.swing.JButton btnViewEditDelete;
    private javax.swing.JLabel lblIcon;
    // End of variables declaration//GEN-END:variables
}
