/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import cafe_management_system.dao.CategoryDao;
import cafe_management_system.model.Category;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Pradnya Jadhav
 */

public class ManageCategory extends javax.swing.JFrame
{
    /**
     * Creates new form ManageCategory
     */
    public ManageCategory()
    {
        initComponents();
        
        setLocationRelativeTo(null);
        jLabel4.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\brownbackground.jpg"));
        btnclose.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\close.png"));
        btnMangeCategory.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\category.png"));
        btnsave.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\save.png"));
        btnclear.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\clear.png"));
        btnsave.setEnabled(false);
        
    }
    public void validateField()
    {
        String category = txtcategory.getText();
        if(!category.equals(""))
        {
            btnsave.setEnabled(true);
        }
        else
        {
            btnsave.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel5 = new javax.swing.JLabel();
        btnMangeCategory = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        btnMangeCategory.setBackground(new java.awt.Color(0, 0, 0));
        btnMangeCategory.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMangeCategory.setForeground(new java.awt.Color(0, 0, 0));
        btnMangeCategory.setText("Manage Category");
        getContentPane().add(btnMangeCategory);
        btnMangeCategory.setBounds(40, 10, 180, 40);

        btnclose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose);
        btnclose.setBounds(650, 10, 40, 40);

        jTable1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Category"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(302, 80, 390, 280);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("View Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 60, 120, 19);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Add New Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 160, 19);

        txtcategory.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtcategory.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtcategoryKeyReleased(evt);
            }
        });
        getContentPane().add(txtcategory);
        txtcategory.setBounds(30, 145, 250, 30);

        btnsave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(80, 190, 140, 40);

        btnclear.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        getContentPane().add(btnclear);
        btnclear.setBounds(80, 250, 140, 40);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("*Click on row to Delete category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 360, 230, 20);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcategoryKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtcategoryKeyReleased
    {//GEN-HEADEREND:event_txtcategoryKeyReleased
        validateField();
       btnsave.setEnabled(true);
    }//GEN-LAST:event_txtcategoryKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsaveActionPerformed
    {//GEN-HEADEREND:event_btnsaveActionPerformed
        Category category = new Category();
        category.setName(txtcategory.getText());
        CategoryDao.save(category);
        setVisible(false);
        new ManageCategory().setVisible(true);
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        ArrayList<Category>list = CategoryDao.getAllRecords();
        Iterator<Category>itr = list.iterator();
        while(itr.hasNext())
        {
            Category categoryObj = itr.next();
            dtm.addRow(new Object[]{categoryObj.getId(),categoryObj.getName()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index,0).toString();
        String name = model.getValueAt(index,1).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete "+name+" category","select",JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            CategoryDao.delete(id); 
            setVisible(false);
            new ManageCategory().setVisible(true);
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncloseActionPerformed
    {//GEN-HEADEREND:event_btncloseActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManageCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManageCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMangeCategory;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcategory;
    // End of variables declaration//GEN-END:variables
}
