
package cafe_management_system;
import cafe_management_system.dao.UserDao;
import cafe_management_system.model.user;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class signup extends javax.swing.JFrame
{
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    public signup()
    {
        initComponents();
        setLocationRelativeTo(null);
        btnsave.setEnabled(false);
       
        jLabel10.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\leftBackground2.png"));
        btnlogin.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\login.png"));
        btnsave.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\save.png"));
        btnclear.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\clear.png"));
        btnexit.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\exit.png"));
    
    }
   public void clear()
   {
       txtname.setText("");
       txtaddress.setText("");
       txtans.setText("");
       txtmail.setText("");
       txtpassword.setText("");
       txtphonenumber.setText("");
       txtsecurity.setText("");
       btnsave.setEnabled(false);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtsecurity = new javax.swing.JTextField();
        txtans = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnforgot = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setMinimumSize(new java.awt.Dimension(1360, 720));
        setPreferredSize(new java.awt.Dimension(1360, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SignUp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(950, 30, 160, 100);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 140, 90, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 190, 60, 26);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 240, 140, 26);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 290, 90, 18);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 340, 100, 18);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Security Question");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 390, 180, 26);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Answer");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(750, 450, 90, 15);

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(920, 140, 380, 30);

        txtmail.setBackground(new java.awt.Color(255, 255, 255));
        txtmail.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtmail.setForeground(new java.awt.Color(0, 0, 0));
        txtmail.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtmail);
        txtmail.setBounds(920, 190, 380, 30);

        txtphonenumber.setBackground(new java.awt.Color(255, 255, 255));
        txtphonenumber.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtphonenumber.setForeground(new java.awt.Color(0, 0, 0));
        txtphonenumber.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtphonenumberKeyReleased(evt);
            }
        });
        getContentPane().add(txtphonenumber);
        txtphonenumber.setBounds(920, 240, 380, 30);

        txtaddress.setBackground(new java.awt.Color(255, 255, 255));
        txtaddress.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 0));
        txtaddress.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtaddressActionPerformed(evt);
            }
        });
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtaddressKeyReleased(evt);
            }
        });
        getContentPane().add(txtaddress);
        txtaddress.setBounds(920, 290, 380, 30);

        txtpassword.setBackground(new java.awt.Color(255, 255, 255));
        txtpassword.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(0, 0, 0));
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(txtpassword);
        txtpassword.setBounds(920, 340, 380, 30);

        txtsecurity.setBackground(new java.awt.Color(255, 255, 255));
        txtsecurity.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtsecurity.setForeground(new java.awt.Color(0, 0, 0));
        txtsecurity.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtsecurityKeyReleased(evt);
            }
        });
        getContentPane().add(txtsecurity);
        txtsecurity.setBounds(920, 390, 380, 30);

        txtans.setBackground(new java.awt.Color(255, 255, 255));
        txtans.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtans.setForeground(new java.awt.Color(0, 0, 0));
        txtans.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtansKeyReleased(evt);
            }
        });
        getContentPane().add(txtans);
        txtans.setBounds(920, 440, 380, 30);

        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(920, 510, 110, 40);

        jPanel1.setBackground(new java.awt.Color(249, 237, 212));
        jPanel1.setMinimumSize(new java.awt.Dimension(1370, 770));
        jPanel1.setLayout(null);

        btnforgot.setBackground(new java.awt.Color(0, 0, 0));
        btnforgot.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnforgot.setForeground(new java.awt.Color(255, 255, 255));
        btnforgot.setText("Forgot Passsword?");
        btnforgot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnforgotActionPerformed(evt);
            }
        });
        jPanel1.add(btnforgot);
        btnforgot.setBounds(240, 570, 150, 40);

        btnlogin.setBackground(new java.awt.Color(0, 0, 0));
        btnlogin.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(470, 570, 150, 40);

        btnexit.setBackground(new java.awt.Color(0, 0, 0));
        btnexit.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(520, 510, 100, 40);

        btnclear.setBackground(new java.awt.Color(0, 0, 0));
        btnclear.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(380, 510, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(680, 0, 680, 720);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -30, 680, 750);

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 0, 680, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtaddressActionPerformed
    {//GEN-HEADEREND:event_txtaddressActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtaddressActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsaveActionPerformed
    {//GEN-HEADEREND:event_btnsaveActionPerformed
       user user= new user();
       user.setName(txtname.getText());
       user.setMail(txtmail.getText());
       user.setMobilenumber(txtphonenumber.getText());
       user.setAddress(txtaddress.getText());
       user.setPassword(txtpassword.getText());
       user.setSecurity(txtsecurity.getText());
       user.setAns(txtans.getText());
       UserDao.save(user);
       
       clear();
    }//GEN-LAST:event_btnsaveActionPerformed

    public void validateFields()
    {
        String name= txtname.getText();
        String email=txtmail.getText();
        String mobilenumber = txtphonenumber.getText();
        String address = txtaddress.getText();
        String password = txtpassword.getText();
        String security =txtsecurity.getText();
        String ans = txtans.getText();
        if(!name.equals("") && email.matches(emailPattern) && mobilenumber.matches(mobileNumberPattern) && mobilenumber.length()== 10 && !address.equals("") && !password.equals("") && !security.equals("") && !ans.equals("") )
        {
            btnsave.setEnabled(true);
        }
        else
        {
            btnsave.setEnabled(false);
        }
    }
    
    
    private void btnexitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnexitActionPerformed
    {//GEN-HEADEREND:event_btnexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnclearActionPerformed
    {//GEN-HEADEREND:event_btnclearActionPerformed
       clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnameKeyReleased
    {//GEN-HEADEREND:event_txtnameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtmailKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtmailKeyReleased
    {//GEN-HEADEREND:event_txtmailKeyReleased
        validateFields();
    }//GEN-LAST:event_txtmailKeyReleased

    private void txtphonenumberKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtphonenumberKeyReleased
    {//GEN-HEADEREND:event_txtphonenumberKeyReleased
      validateFields();
    }//GEN-LAST:event_txtphonenumberKeyReleased

    private void txtaddressKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtaddressKeyReleased
    {//GEN-HEADEREND:event_txtaddressKeyReleased
       validateFields();
    }//GEN-LAST:event_txtaddressKeyReleased

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtpasswordKeyReleased
    {//GEN-HEADEREND:event_txtpasswordKeyReleased
       validateFields();
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtsecurityKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtsecurityKeyReleased
    {//GEN-HEADEREND:event_txtsecurityKeyReleased
        validateFields();
    }//GEN-LAST:event_txtsecurityKeyReleased

    private void txtansKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtansKeyReleased
    {//GEN-HEADEREND:event_txtansKeyReleased
         validateFields();
    }//GEN-LAST:event_txtansKeyReleased

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnloginActionPerformed
    {//GEN-HEADEREND:event_btnloginActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnforgotActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnforgotActionPerformed
    {//GEN-HEADEREND:event_btnforgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnforgotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                
                new signup().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforgot;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtans;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtsecurity;
    // End of variables declaration//GEN-END:variables
}
