/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import cafe_management_system.dao.CategoryDao;
import cafe_management_system.dao.ProductDao;
import cafe_management_system.model.Category;
import cafe_management_system.model.Product;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Pradnya Jadhav
 */
public class viewEditDeleteProduct extends javax.swing.JFrame
{

    /**
     * Creates new form viewEditDeleteProduct
     */
    public viewEditDeleteProduct()
    {
        initComponents();
        setLocationRelativeTo(this);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        jLabel2.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\brownbackground.jpg"));
        btnexit.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\close.png"));
        btndelete.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\delete.png"));
        btnclear.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\clear.png"));
        btnupdate.setIcon(new ImageIcon("C:\\Users\\Pradnya Jadhav\\Documents\\NetBeansProjects\\src\\main\\mavenproject1\\src\\main\\java\\cafe_management_system\\image\\update.png"));
    }
    public void validateField()
    {
        String name = txtName.getText();
        String price = txtPrice.getText();
        String category = (String)jComboBox1.getSelectedItem();
        if(!name.equals("") && !price.equals("") && category != null)
        {
            btnupdate.setEnabled(true);
        }
        else
        {
            btnupdate.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblId = new java.awt.Label();
        lblName = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        txtName = new java.awt.TextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1290, 600));
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        lblId.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId);
        lblId.setBounds(103, 102, 30, 40);

        lblName.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        lblName.setText("Name");
        getContentPane().add(lblName);
        lblName.setBounds(100, 160, 70, 34);

        label3.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        label3.setText("Category");
        getContentPane().add(label3);
        label3.setBounds(100, 230, 130, 34);

        label4.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        label4.setText("Price");
        getContentPane().add(label4);
        label4.setBounds(100, 290, 80, 34);

        label5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        label5.setText("00");
        getContentPane().add(label5);
        label5.setBounds(250, 110, 30, 27);

        txtName.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(240, 160, 260, 30);

        jComboBox1.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 230, 260, 30);

        txtPrice.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice);
        txtPrice.setBounds(240, 290, 260, 36);

        btnupdate.setBackground(new java.awt.Color(0, 0, 0));
        btnupdate.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(100, 380, 120, 40);

        btndelete.setBackground(new java.awt.Color(0, 0, 0));
        btndelete.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(270, 380, 120, 40);

        btnclear.setBackground(new java.awt.Color(0, 0, 0));
        btnclear.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(430, 380, 120, 40);

        jTable1.setFont(new java.awt.Font("Aparajita", 0, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Name", "Category", "Price"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 60, 620, 480);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("View,  Edit & Delete Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 290, 40);

        btnexit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit);
        btnexit.setBounds(1230, 0, 40, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndeleteActionPerformed
    {//GEN-HEADEREND:event_btndeleteActionPerformed
        String id = lblId.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete this product" , "Select",JOptionPane.YES_NO_OPTION);
        if( a==0)
        {
            ProductDao.delete(id);
            setVisible(false);
            new viewEditDeleteProduct().setVisible(true);
            
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNameKeyReleased
    {//GEN-HEADEREND:event_txtNameKeyReleased
      validateField();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPriceKeyReleased
    {//GEN-HEADEREND:event_txtPriceKeyReleased
        validateField();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceKeyReleased

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnupdateActionPerformed
    {//GEN-HEADEREND:event_btnupdateActionPerformed
        Product product = new Product();
        int id = Integer.parseInt(lblId.getText());
        product.setId(id);
        product.setName(txtName.getText());
        product.setCategory((String)jComboBox1.getSelectedItem() );
        product.setPrice(txtPrice.getText());
        ProductDao.update(product);
        setVisible(false);
        new viewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
       
        ArrayList<Category>list = CategoryDao.getAllRecords();
        Iterator<Category>itr = list.iterator();
        while(itr.hasNext())
        {
            Category categoryObj = itr.next();
            jComboBox1.addItem(categoryObj.getName());
        }
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        ArrayList<Product> list1 = ProductDao.getAllRecords();
        Iterator<Product> itr1 = list1.iterator();
        while(itr1.hasNext())
        {
            Product productObj = itr1.next();
            dtm.addRow(new Object[] {productObj.getId(),productObj.getName(),productObj.getCategory(),productObj.getPrice()});
            
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTable1MouseClicked
    {//GEN-HEADEREND:event_jTable1MouseClicked
       int index = jTable1.getSelectedRow();
       TableModel model = jTable1.getModel();
       String id = model.getValueAt(index,0).toString();
       lblId.setText(id);
       String name = model.getValueAt(index,1).toString();
       txtName.setText(name);
       String category = model.getValueAt(index,2).toString();
       String price = model.getValueAt(index, 3).toString();
       txtPrice.setText(price);
       btnupdate.setEnabled(true);
       btndelete.setEnabled(true);
       jComboBox1.removeAllItems();
       jComboBox1.addItem(category);
       ArrayList<Category> categoryList = CategoryDao.getAllRecords();
       Iterator<Category> categoryItr = categoryList.iterator();
       while(categoryItr.hasNext())
       {
           Category categoryObj = categoryItr.next();
           if(!categoryObj.getName().equals(category))
               jComboBox1.addItem(categoryObj.getName());
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnclearActionPerformed
    {//GEN-HEADEREND:event_btnclearActionPerformed
            setVisible(false);
            new viewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnclearActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnexitActionPerformed
    {//GEN-HEADEREND:event_btnexitActionPerformed
        setVisible(false);
        new  home().setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(viewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(viewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(viewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(viewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new viewEditDeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label lblId;
    private java.awt.Label lblName;
    private java.awt.TextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
